server:
  port: 8080
  url: http://localhost:8080

app:
  resourceLocations:
    images: E:\User\SobstvennoYz\Pictures\download

spring:
#  application:
#    name: photogallery

  datasource:
    url: jdbc:postgresql://localhost:5432/photogallery_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12344321
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


  web:
    resources:
      static-locations: "classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:

file:
  upload-dir: "E:/User/SobstvennoYz/Pictures/download"

logging:
  level:
    ru.top_academy.photogallery: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
