server:
  port: 8080

app:
  resourceLocations:
    images: E:\User\SobstvennoYz\Pictures\download

spring:
#  application:
#    name: photogallery

  datasource:
    url: jdbc:postgresql://localhost:5432/photogallery_db
    username: postgres
    password: 12344321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
      format_sql: true

  web:
    resources:
      static-locations: "classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/"
      file:
        upload-dir: uploads
      add-mappings: false

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
#    path: /swagger-ui.html

    # Настройки для загрузки файлов
#      file.upload-dir=uploads
      spring.servlet.multipart.max-file-size=10MB
      spring.servlet.multipart.max-request-size=10MB
      server.url=http://localhost:8080
